name: Atualizar contador

on:
  push:
    branches: [ 'main' ]
    paths: [ 'participantes/*/docker-compose.yml' ]
  workflow_dispatch:

env:
  NODE_VERSION: 20.5.1

jobs:
  atualiza-contador:
    name: Atualizar o contador de participantes
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout da branch
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Atualiza o SVG do contador
        run: node index.js ../../participantes/ ../../misc/contador-de-participantes.svg
        working-directory: './scripts/contador-de-participantes'

      - name: Comita o SVG atualizado
        uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9.1.3
        with:
          add: 'misc/contador-participantes.svg'
          default_author: github_actions
          message: "Contador de participantes atualizado."
