name: Novas submissões

on:
  push:
    branches:
    - 'main'
    paths:
      - './participantes/*'

jobs:
  novas-ou-alterados:
    name: Descobre submissões novas ou alteradas
    runs-on: 'ubuntu-22.04'

    outputs:
      matrix: ${{ steps.submissoes.outputs.matrix }}

    steps:
    - name: Checkout da branch
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        fetch-depth: 50

    - name: Instala o git e curl # por que não vem instalado nessa joça
      run: apt-get update -qq && apt-get install -qq -y git curl

    - name: Instala jq
      run: |
        curl -fsSL https://github.com/jqlang/jq/releases/download/jq-1.7rc1/jq-linux-amd64 >> /usr/bin/jq
        chmod +x /usr/bin/jq

    - name: Descobre diretório das submissões
      id: submissoes
      run: |
        DIRETORIOS=$(git diff --name-only HEAD~1 | grep docker-compose.y | xargs dirname % | grep "^participantes/")
        MATRIX=$(echo ${DIRETORIOS} | jq --raw-input . | jq --slurp '{diretorio: .}' | jq -r tostring)
        echo "::set-output name=matrix::${MATRIX}"

  rodar-gatling:
    name: Roda o Gatling para as submissões descobertas
    # runs-on: 'self-hosted'
    runs-on: 'ubuntu-22.04'

    needs:
      - 'novas-ou-alterados'

    if: ${{ needs.novas-ou-alterados.outputs.matrix != '{"diretorio":[]}'}}

    strategy:
      matrix: ${{ fromJson(needs.novas-ou-alterados.outputs.matrix) }}

    steps:
    # - name: Checkout da branch
    #   uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Roda ${{ matrix.diretorio }}
      run: |
        echo "foo"
        echo "${{ matrix.diretorio }}"
        echo "bar"
